static-file-name-checker

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,13 +52,10 @@ jobs:
 
           # Find invalid filenames
           invalid_kebab_case=$(echo "$changed_files" | grep -vE '^([a-z0-9]+(-[a-z0-9]+)*)(/([a-z0-9]+(-[a-z0-9]+)*))*\.(md|jpg|png|jpeg|svg)$' || true)
-          # Find long filenames
-          long_files=$(echo "$changed_files" | awk 'length > 100')
-          failure_flag=0
 
           # Check for  filenames that are not in kebab case
           if [ -n "$invalid_kebab_case" ]; then
-            echo -e "${Blue} The following filenames are not in kebab case:${Reset}"
+            echo -e "${Blue} The following path is not  in kebab case:${Reset}"
             x=1
             echo "$invalid_kebab_case" | while read -r file; do
               echo -e "${Red}$x. $file${Reset}"
@@ -67,4 +64,26 @@ jobs:
             failure_flag=1
           else
             echo -e "${Green} All changed filenames are  in kebab case."
+          fi
+
+          changed_files=$(git diff --name-only HEAD^1 HEAD | grep -E '\.(md|jpg|png|jpeg|svg)$')
+          long_files=$(echo "$changed_files" | awk 'length > 100')
+          # Check for Markdown filenames that are not long
+           if [ -n "$long_files" ]; then
+            echo -e "${Blue} The following Markdown filenames exceed 100 characters:${Reset}"
+             x=1
+            echo "$long_files$" | while read -r file; do
+              echo -e "${Red}$x. $long_files${Reset}"
+              x=$((x + 1))
+            done
+            failure_flag=1
+           else
+            echo -e "${Green} All changed Markdown filenames are  of valid length.${Reset}"
+          fi
+          if [ "$failure_flag" -eq 0 ]; then
+            echo -e "${Green} All changed Markdown filenames passed validation.${Reset}"
+            exit 0
+          else
+            echo -e "${Red} The check has failed.${Reset}"
+            exit 1
           fi
